# Generated by Django 3.1 on 2020-10-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='DP',
            field=models.ImageField(blank=True, null=True, upload_to='images/DP/'),
        ),
    ]
