# Generated by Django 3.0.3 on 2020-10-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_customer_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='DP',
        ),
    ]
