# Generated by Django 3.1 on 2020-10-05 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PetService', '0001_initial'),
        ('PetShop', '0001_initial'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.customer')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetService.service')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.customer')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetShop.addproduct')),
            ],
        ),
    ]
