# Generated by Django 3.1 on 2020-10-05 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PetService', '0001_initial'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('pet_type', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.customer')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='PetService.service')),
            ],
        ),
    ]
