# Generated by Django 3.0.3 on 2020-10-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceOrder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
