# Generated by Django 3.1 on 2020-10-07 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(blank=True, default='products/images/default.jpg', upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
