# Generated by Django 3.1 on 2020-10-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0002_auto_20201007_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
