# Generated by Django 3.0.3 on 2020-10-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0004_orderproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='payment',
            field=models.CharField(choices=[('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=30),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
